export const data  = [
    {id:1,title:'Winter body', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:2,title:'Adidas', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:80, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item2.8779dd15.jpg"},
    {id:3,title:'Vans', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:120, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item6.f5fd97b5.jpg"},
    {id:4,title:'White', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:260, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item4.65bc33d7.jpg"},
    {id:5,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:6,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:7,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:8,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:9,title:'Winter body', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:10,title:'Adidas', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:80, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item2.8779dd15.jpg"},
    {id:11,title:'Vans', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:120, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item6.f5fd97b5.jpg"},
    {id:12,title:'White', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:260, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item4.65bc33d7.jpg"},
    {id:13,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:14,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:15,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:16,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:17,title:'Winter body', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:18,title:'Adidas', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:80, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item2.8779dd15.jpg"},
    {id:19,title:'Vans', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:120, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item6.f5fd97b5.jpg"},
    {id:20,title:'White', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:260, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item4.65bc33d7.jpg"},
    {id:21,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:22,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:23,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:24,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:25,title:'Winter body', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:26,title:'Adidas', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:80, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item2.8779dd15.jpg"},
    {id:27,title:'Vans', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:120, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item6.f5fd97b5.jpg"},
    {id:28,title:'White', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:260, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item4.65bc33d7.jpg"},
    {id:29,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:30,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:31,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:32,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:33,title:'Winter body', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:34,title:'Adidas', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:80, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item2.8779dd15.jpg"},
    {id:35,title:'Vans', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:120, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item6.f5fd97b5.jpg"},
    {id:36,title:'White', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:260, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item4.65bc33d7.jpg"},
    {id:37,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:38,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:39,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:40,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:41,title:'Winter body', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:42,title:'Adidas', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:80, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item2.8779dd15.jpg"},
    {id:43,title:'Vans', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:120, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item6.f5fd97b5.jpg"},
    {id:44,title:'White', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:260, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item4.65bc33d7.jpg"},
    {id:45,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:46,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:47,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:48,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"},
    {id:49,title:'Cropped-sho', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:160, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item3.9bd2546f.jpg"},
    {id:50,title:'Blues', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",price:90, img: "https://my-shopping-cart-leawwzhsmf.now.sh/static/media/item1.6c426583.jpg"}
  ];